//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectServicesEndpoint
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="https://localhost.priority1.uk.net/Priority1WebServices/JSON", ItemName="int")]
    internal class ArrayOfInt : System.Collections.Generic.List<int>
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://localhost.priority1.uk.net/Priority1WebServices/JSON", ConfigurationName="ProjectServicesEndpoint.API_ProjectServicesSoap")]
    internal interface API_ProjectServicesSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://localhost.priority1.uk.net/Priority1WebServices/JSON/GetAPIToken", ReplyAction="*")]
        System.Threading.Tasks.Task<ProjectServicesEndpoint.GetAPITokenResponse> GetAPITokenAsync(ProjectServicesEndpoint.GetAPITokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://localhost.priority1.uk.net/Priority1WebServices/JSON/GetProjectDetail", ReplyAction="*")]
        System.Threading.Tasks.Task<ProjectServicesEndpoint.GetProjectDetailResponse> GetProjectDetailAsync(ProjectServicesEndpoint.GetProjectDetailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://localhost.priority1.uk.net/Priority1WebServices/JSON/GetProjectDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<ProjectServicesEndpoint.GetProjectDetailsResponse> GetProjectDetailsAsync(ProjectServicesEndpoint.GetProjectDetailsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetAPITokenRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAPIToken", Namespace="https://localhost.priority1.uk.net/Priority1WebServices/JSON", Order=0)]
        public ProjectServicesEndpoint.GetAPITokenRequestBody Body;
        
        public GetAPITokenRequest()
        {
        }
        
        public GetAPITokenRequest(ProjectServicesEndpoint.GetAPITokenRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://localhost.priority1.uk.net/Priority1WebServices/JSON")]
    internal partial class GetAPITokenRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string loginName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public GetAPITokenRequestBody()
        {
        }
        
        public GetAPITokenRequestBody(string loginName, string password)
        {
            this.loginName = loginName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetAPITokenResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAPITokenResponse", Namespace="https://localhost.priority1.uk.net/Priority1WebServices/JSON", Order=0)]
        public ProjectServicesEndpoint.GetAPITokenResponseBody Body;
        
        public GetAPITokenResponse()
        {
        }
        
        public GetAPITokenResponse(ProjectServicesEndpoint.GetAPITokenResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://localhost.priority1.uk.net/Priority1WebServices/JSON")]
    internal partial class GetAPITokenResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAPITokenResult;
        
        public GetAPITokenResponseBody()
        {
        }
        
        public GetAPITokenResponseBody(string GetAPITokenResult)
        {
            this.GetAPITokenResult = GetAPITokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetProjectDetailRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProjectDetail", Namespace="https://localhost.priority1.uk.net/Priority1WebServices/JSON", Order=0)]
        public ProjectServicesEndpoint.GetProjectDetailRequestBody Body;
        
        public GetProjectDetailRequest()
        {
        }
        
        public GetProjectDetailRequest(ProjectServicesEndpoint.GetProjectDetailRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://localhost.priority1.uk.net/Priority1WebServices/JSON")]
    internal partial class GetProjectDetailRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string apiToken;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int projectID;
        
        public GetProjectDetailRequestBody()
        {
        }
        
        public GetProjectDetailRequestBody(string apiToken, int projectID)
        {
            this.apiToken = apiToken;
            this.projectID = projectID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetProjectDetailResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProjectDetailResponse", Namespace="https://localhost.priority1.uk.net/Priority1WebServices/JSON", Order=0)]
        public ProjectServicesEndpoint.GetProjectDetailResponseBody Body;
        
        public GetProjectDetailResponse()
        {
        }
        
        public GetProjectDetailResponse(ProjectServicesEndpoint.GetProjectDetailResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://localhost.priority1.uk.net/Priority1WebServices/JSON")]
    internal partial class GetProjectDetailResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetProjectDetailResult;
        
        public GetProjectDetailResponseBody()
        {
        }
        
        public GetProjectDetailResponseBody(string GetProjectDetailResult)
        {
            this.GetProjectDetailResult = GetProjectDetailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetProjectDetailsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProjectDetails", Namespace="https://localhost.priority1.uk.net/Priority1WebServices/JSON", Order=0)]
        public ProjectServicesEndpoint.GetProjectDetailsRequestBody Body;
        
        public GetProjectDetailsRequest()
        {
        }
        
        public GetProjectDetailsRequest(ProjectServicesEndpoint.GetProjectDetailsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://localhost.priority1.uk.net/Priority1WebServices/JSON")]
    internal partial class GetProjectDetailsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string apiToken;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string projectName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ProjectServicesEndpoint.ArrayOfInt businessUnitIDs;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<bool> activeOnly;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int startRow;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int pageSize;
        
        public GetProjectDetailsRequestBody()
        {
        }
        
        public GetProjectDetailsRequestBody(string apiToken, string projectName, ProjectServicesEndpoint.ArrayOfInt businessUnitIDs, System.Nullable<bool> activeOnly, int startRow, int pageSize)
        {
            this.apiToken = apiToken;
            this.projectName = projectName;
            this.businessUnitIDs = businessUnitIDs;
            this.activeOnly = activeOnly;
            this.startRow = startRow;
            this.pageSize = pageSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetProjectDetailsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProjectDetailsResponse", Namespace="https://localhost.priority1.uk.net/Priority1WebServices/JSON", Order=0)]
        public ProjectServicesEndpoint.GetProjectDetailsResponseBody Body;
        
        public GetProjectDetailsResponse()
        {
        }
        
        public GetProjectDetailsResponse(ProjectServicesEndpoint.GetProjectDetailsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://localhost.priority1.uk.net/Priority1WebServices/JSON")]
    internal partial class GetProjectDetailsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetProjectDetailsResult;
        
        public GetProjectDetailsResponseBody()
        {
        }
        
        public GetProjectDetailsResponseBody(string GetProjectDetailsResult)
        {
            this.GetProjectDetailsResult = GetProjectDetailsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    internal interface API_ProjectServicesSoapChannel : ProjectServicesEndpoint.API_ProjectServicesSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    internal partial class API_ProjectServicesSoapClient : System.ServiceModel.ClientBase<ProjectServicesEndpoint.API_ProjectServicesSoap>, ProjectServicesEndpoint.API_ProjectServicesSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public API_ProjectServicesSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(API_ProjectServicesSoapClient.GetBindingForEndpoint(endpointConfiguration), API_ProjectServicesSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public API_ProjectServicesSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(API_ProjectServicesSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public API_ProjectServicesSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(API_ProjectServicesSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public API_ProjectServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProjectServicesEndpoint.GetAPITokenResponse> ProjectServicesEndpoint.API_ProjectServicesSoap.GetAPITokenAsync(ProjectServicesEndpoint.GetAPITokenRequest request)
        {
            return base.Channel.GetAPITokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProjectServicesEndpoint.GetAPITokenResponse> GetAPITokenAsync(string loginName, string password)
        {
            ProjectServicesEndpoint.GetAPITokenRequest inValue = new ProjectServicesEndpoint.GetAPITokenRequest();
            inValue.Body = new ProjectServicesEndpoint.GetAPITokenRequestBody();
            inValue.Body.loginName = loginName;
            inValue.Body.password = password;
            return ((ProjectServicesEndpoint.API_ProjectServicesSoap)(this)).GetAPITokenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProjectServicesEndpoint.GetProjectDetailResponse> ProjectServicesEndpoint.API_ProjectServicesSoap.GetProjectDetailAsync(ProjectServicesEndpoint.GetProjectDetailRequest request)
        {
            return base.Channel.GetProjectDetailAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProjectServicesEndpoint.GetProjectDetailResponse> GetProjectDetailAsync(string apiToken, int projectID)
        {
            ProjectServicesEndpoint.GetProjectDetailRequest inValue = new ProjectServicesEndpoint.GetProjectDetailRequest();
            inValue.Body = new ProjectServicesEndpoint.GetProjectDetailRequestBody();
            inValue.Body.apiToken = apiToken;
            inValue.Body.projectID = projectID;
            return ((ProjectServicesEndpoint.API_ProjectServicesSoap)(this)).GetProjectDetailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProjectServicesEndpoint.GetProjectDetailsResponse> ProjectServicesEndpoint.API_ProjectServicesSoap.GetProjectDetailsAsync(ProjectServicesEndpoint.GetProjectDetailsRequest request)
        {
            return base.Channel.GetProjectDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProjectServicesEndpoint.GetProjectDetailsResponse> GetProjectDetailsAsync(string apiToken, string projectName, ProjectServicesEndpoint.ArrayOfInt businessUnitIDs, System.Nullable<bool> activeOnly, int startRow, int pageSize)
        {
            ProjectServicesEndpoint.GetProjectDetailsRequest inValue = new ProjectServicesEndpoint.GetProjectDetailsRequest();
            inValue.Body = new ProjectServicesEndpoint.GetProjectDetailsRequestBody();
            inValue.Body.apiToken = apiToken;
            inValue.Body.projectName = projectName;
            inValue.Body.businessUnitIDs = businessUnitIDs;
            inValue.Body.activeOnly = activeOnly;
            inValue.Body.startRow = startRow;
            inValue.Body.pageSize = pageSize;
            return ((ProjectServicesEndpoint.API_ProjectServicesSoap)(this)).GetProjectDetailsAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.API_ProjectServicesSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.API_ProjectServicesSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.API_ProjectServicesSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://anz.fieldview.viewpoint.com/FieldViewWebServices/WebServices/JSON/API_Pro" +
                        "jectServices.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.API_ProjectServicesSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://anz.fieldview.viewpoint.com/FieldViewWebServices/WebServices/JSON/API_Pro" +
                        "jectServices.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            API_ProjectServicesSoap,
            
            API_ProjectServicesSoap12,
        }
    }
}
